# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/assertoor.yaml.j2

assertoor:
  fullnameOverride: assertoor

  image:
    repository: ethpandaops/assertoor
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi

  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.0.js" integrity="sha384-j6D+DanVUQs7XYmJaMXGwg2VdBq07F/ekc+bP5CNPsLOYCv4TKf8r3JBWqxwakKL" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: assertoor.nft-devnet-10.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  ingressAdmin:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: assertoor-admin.nft-devnet-10.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  persistence:
    enabled: true

  endpoints:
    - name:  bootnode-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-bootnode-1.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-bootnode-1.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-besu-1.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-besu-1.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-besu-2
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-besu-2.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-besu-2.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-erigon-1.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-erigon-1.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-erigon-2
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-erigon-2.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-erigon-2.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-geth-1.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-geth-1.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-geth-2
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-geth-2.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-geth-2.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nethermind-1.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-nethermind-1.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-nethermind-2
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nethermind-2.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-nethermind-2.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-nimbusel-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nimbusel-1.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-nimbusel-1.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-nimbusel-2
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nimbusel-2.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-nimbusel-2.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-reth-1.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-reth-1.srv.nft-devnet-10.ethpandaops.io
    - name:  lighthouse-reth-2
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-reth-2.srv.nft-devnet-10.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@bn-lighthouse-reth-2.srv.nft-devnet-10.ethpandaops.io

  validatorNamesInventory: https://config.nft-devnet-10.ethpandaops.io/api/v1/nodes/validator-ranges
  globalVariables:
    walletPrivkey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.assertoor_private_key}>"
    clientPairNames:
      - bootnode-1
      - lighthouse-besu-1
      - lighthouse-besu-2
      - lighthouse-erigon-1
      - lighthouse-erigon-2
      - lighthouse-geth-1
      - lighthouse-geth-2
      - lighthouse-nethermind-1
      - lighthouse-nethermind-2
      - lighthouse-nimbusel-1
      - lighthouse-nimbusel-2
      - lighthouse-reth-1
      - lighthouse-reth-2
    validatorPairNames:
      - lighthouse-besu-1
      - lighthouse-besu-2
      - lighthouse-erigon-1
      - lighthouse-erigon-2
      - lighthouse-geth-2
      - lighthouse-nethermind-1
      - lighthouse-nethermind-2
      - lighthouse-nimbusel-1
      - lighthouse-nimbusel-2
      - lighthouse-reth-1
      - lighthouse-reth-2

  assertoorTests: []