# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/spamoor.yaml.j2

spamoor:
  fullnameOverride: spamoor
  image:
    repository: ethpandaops/spamoor
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.0.js" integrity="sha384-j6D+DanVUQs7XYmJaMXGwg2VdBq07F/ekc+bP5CNPsLOYCv4TKf8r3JBWqxwakKL" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: spamoor.nft-devnet-10.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  customArgs:
    - --fulu-activation=1770721584

  persistence:
    enabled: true

  privateKey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.spamoor_private_key}>"
  rpcEndpoints:
  # Rpc
  - "http://geth-prysm-001:8545"
  - "group(bootnode-1)name(bootnode-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-bootnode-1.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-besu-1)name(lighthouse-besu-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-besu-1.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-besu-2)name(lighthouse-besu-2)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-besu-2.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-erigon-1)name(lighthouse-erigon-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-erigon-1.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-erigon-2)name(lighthouse-erigon-2)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-erigon-2.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-geth-1)name(lighthouse-geth-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-geth-1.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-geth-2)name(lighthouse-geth-2)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-geth-2.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-nethermind-1)name(lighthouse-nethermind-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nethermind-1.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-nethermind-2)name(lighthouse-nethermind-2)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nethermind-2.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-nimbusel-1)name(lighthouse-nimbusel-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nimbusel-1.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-nimbusel-2)name(lighthouse-nimbusel-2)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nimbusel-2.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-reth-1)name(lighthouse-reth-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-reth-1.srv.nft-devnet-10.ethpandaops.io"
  - "group(lighthouse-reth-2)name(lighthouse-reth-2)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-reth-2.srv.nft-devnet-10.ethpandaops.io"
  - "group(lodestar-geth-1)name(lodestar-geth-1)https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lodestar-geth-1.srv.nft-devnet-10.ethpandaops.io"
