# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/forkmon.yaml.j2

forkmon:
  fullnameOverride: forkmon
  image:
    repository: skylenet/nodemonitor
    tag: darkmode
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.0.js" integrity="sha384-j6D+DanVUQs7XYmJaMXGwg2VdBq07F/ekc+bP5CNPsLOYCv4TKf8r3JBWqxwakKL" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: forkmon.nft-devnet-10.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  network: nft-devnet-10
  endpoints:
  # Rpc
  - addr: http://geth-prysm-001:8545
    name: rpc-prysm-geth-001
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-bootnode-1.srv.nft-devnet-10.ethpandaops.io
    name: bootnode-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-besu-1.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-besu-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-besu-2.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-besu-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-erigon-1.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-erigon-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-erigon-2.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-erigon-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-geth-1.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-geth-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-geth-2.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-geth-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nethermind-1.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-nethermind-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nethermind-2.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-nethermind-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nimbusel-1.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-nimbusel-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-nimbusel-2.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-nimbusel-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-reth-1.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-reth-1
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lighthouse-reth-2.srv.nft-devnet-10.ethpandaops.io
    name: lighthouse-reth-2
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.nft-devnets.node_ingress.combined}>@rpc-lodestar-geth-1.srv.nft-devnet-10.ethpandaops.io
    name: lodestar-geth-1

  config: |
    # How often to reload data from the nodes
    reload_interval = "10s"
    # If specified, a http server will serve static content here
    server_address = "0.0.0.0:{{ .Values.httpPort}}"
    # Shown in the document title, if specified
    chain_name="{{ .Values.network }}"
    # Local or non third party connection require rpc kind
    {{- range .Values.endpoints }}
    [[clients]]
      url  = {{ .addr | quote }}
      name = {{ .name | quote }}
      kind = "rpc"
    {{- end }}
