# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

prysm-geth-001:
  global:
    main:
      network: nft-devnet-10
      engineEndpoint: http://geth-prysm-001:8551
      rpcEndpoint: http://geth-prysm-001:8545
      beaconEndpoint: http://prysm-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        nft-devnet-10: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.template-devnets.node_ingress.combined}>@bn-bootnode-1.nft-devnet-10.ethpandaops.io
    clientArgs:
      networks:
        nft-devnet-10:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://d12e9b11f9dd556a68f37573534e400c3fd44ed0f70dcbfc936084f5fe5338ea4cf26de188ef1064b5d0c11284ee3271ca4f31c89c219464b398b10ef245f2da@46.225.118.77:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --bonsai-limit-trie-logs-enabled=false
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://d12e9b11f9dd556a68f37573534e400c3fd44ed0f70dcbfc936084f5fe5338ea4cf26de188ef1064b5d0c11284ee3271ca4f31c89c219464b398b10ef245f2da@46.225.118.77:30303?discport=30303
              - --Pruning.Mode=None
              - --config=none
              - --log=INFO
              - --Seq.MinLevel=Info
              - --Seq.ServerUrl=https://seq.nethermind.io
              - --Seq.ApiKey=yuOqjKOHhZCw2D2U7pmL
              - --Metrics.PushGatewayUrl=http://94.237.52.161:9000/metrics/nethermind-iudiy4raagaizaih1phuaShekighoJ2ixaecahvii7ohte3oozeeh0eTh7Aich1Shee9ceetuy3iGhexoh5naithoot8rebi7fee
            geth:
              - --http.api=eth,net,web3,debug,admin,txpool
              - --http.vhosts=*
              - --networkid=7062601735
              - --syncmode=full
              - --bootnodes=enode://d12e9b11f9dd556a68f37573534e400c3fd44ed0f70dcbfc936084f5fe5338ea4cf26de188ef1064b5d0c11284ee3271ca4f31c89c219464b398b10ef245f2da@46.225.118.77:30303?discport=30303
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --networkid=7062601735
              - --db.size.limit=500GB
              - --bootnodes=enode://d12e9b11f9dd556a68f37573534e400c3fd44ed0f70dcbfc936084f5fe5338ea4cf26de188ef1064b5d0c11284ee3271ca4f31c89c219464b398b10ef245f2da@46.225.118.77:30303?discport=30303
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QABQCogMC5EhQIIDFZqScK2GTQ29G2WiK1gLg07svKdOYtB8cliJrvnCCZl-M5OG2LXDoh6dQgbo0xUUdTWayw2GAZxHAr_XgmlkgnY0gmlwhC7hdk2Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-MC4QIN8eRLtg-vbgm1WjYwhd2Lwr23Rju0yAaN-aZoIJpGxUygZ22ehBy6a4_LW6jUnQPTndpcCus6s9iziHYhfQ5MHh2F0dG5ldHOIgAEAAAAAAACDY2djBIRldGgykNn6ZuBwUQlRAQAAAAAAAACCaWSCdjSCaXCELuF2TYNuZmSE5h3jZolzZWNwMjU2azGhAnW4Uzhshww8HqAXq11KJLNGyCfEkCnZQFJxajgonf6vg3RjcIIjKIN1ZHCCIyg
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QABQCogMC5EhQIIDFZqScK2GTQ29G2WiK1gLg07svKdOYtB8cliJrvnCCZl-M5OG2LXDoh6dQgbo0xUUdTWayw2GAZxHAr_XgmlkgnY0gmlwhC7hdk2Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-MC4QIN8eRLtg-vbgm1WjYwhd2Lwr23Rju0yAaN-aZoIJpGxUygZ22ehBy6a4_LW6jUnQPTndpcCus6s9iziHYhfQ5MHh2F0dG5ldHOIgAEAAAAAAACDY2djBIRldGgykNn6ZuBwUQlRAQAAAAAAAACCaWSCdjSCaXCELuF2TYNuZmSE5h3jZolzZWNwMjU2azGhAnW4Uzhshww8HqAXq11KJLNGyCfEkCnZQFJxajgonf6vg3RjcIIjKIN1ZHCCIyg
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QABQCogMC5EhQIIDFZqScK2GTQ29G2WiK1gLg07svKdOYtB8cliJrvnCCZl-M5OG2LXDoh6dQgbo0xUUdTWayw2GAZxHAr_XgmlkgnY0gmlwhC7hdk2Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QIN8eRLtg-vbgm1WjYwhd2Lwr23Rju0yAaN-aZoIJpGxUygZ22ehBy6a4_LW6jUnQPTndpcCus6s9iziHYhfQ5MHh2F0dG5ldHOIgAEAAAAAAACDY2djBIRldGgykNn6ZuBwUQlRAQAAAAAAAACCaWSCdjSCaXCELuF2TYNuZmSE5h3jZolzZWNwMjU2azGhAnW4Uzhshww8HqAXq11KJLNGyCfEkCnZQFJxajgonf6vg3RjcIIjKIN1ZHCCIyg
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QABQCogMC5EhQIIDFZqScK2GTQ29G2WiK1gLg07svKdOYtB8cliJrvnCCZl-M5OG2LXDoh6dQgbo0xUUdTWayw2GAZxHAr_XgmlkgnY0gmlwhC7hdk2Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-MC4QIN8eRLtg-vbgm1WjYwhd2Lwr23Rju0yAaN-aZoIJpGxUygZ22ehBy6a4_LW6jUnQPTndpcCus6s9iziHYhfQ5MHh2F0dG5ldHOIgAEAAAAAAACDY2djBIRldGgykNn6ZuBwUQlRAQAAAAAAAACCaWSCdjSCaXCELuF2TYNuZmSE5h3jZolzZWNwMjU2azGhAnW4Uzhshww8HqAXq11KJLNGyCfEkCnZQFJxajgonf6vg3RjcIIjKIN1ZHCCIyg
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=INFO
              - --light-client-data-serve=false
              - --bootstrap-node=enr:-Iq4QABQCogMC5EhQIIDFZqScK2GTQ29G2WiK1gLg07svKdOYtB8cliJrvnCCZl-M5OG2LXDoh6dQgbo0xUUdTWayw2GAZxHAr_XgmlkgnY0gmlwhC7hdk2Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-MC4QIN8eRLtg-vbgm1WjYwhd2Lwr23Rju0yAaN-aZoIJpGxUygZ22ehBy6a4_LW6jUnQPTndpcCus6s9iziHYhfQ5MHh2F0dG5ldHOIgAEAAAAAAACDY2djBIRldGgykNn6ZuBwUQlRAQAAAAAAAACCaWSCdjSCaXCELuF2TYNuZmSE5h3jZolzZWNwMjU2azGhAnW4Uzhshww8HqAXq11KJLNGyCfEkCnZQFJxajgonf6vg3RjcIIjKIN1ZHCCIyg


  geth:
    enabled: true
    fullnameOverride: geth-prysm-001
    image:
      repository: ethereum/client-go
      tag: latest
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31401
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: nft-devnet-10
      testnet: nft-devnet-10
      ethereum_network: nft-devnet-10
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.nft-devnet-10.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.nft-devnet-10.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.nft-devnet-10.ethpandaops.io/el/besu.json;
            ENODES_URI=https://config.nft-devnet-10.ethpandaops.io/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethereum/client-go:latest
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  prysm:
    checkpointSync:
      enabled: false
      addresses:
        nft-devnet-10: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.template-devnets.node_ingress.combined}>@bn-bootnode-1.nft-devnet-10.ethpandaops.io
    enabled: true
    fullnameOverride: prysm-geth-001
    image:
      repository: gcr.io/prysmaticlabs/prysm/beacon-chain
      tag: stable
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32401
    podLabels:
      network: nft-devnet-10
      testnet: nft-devnet-10
      ethereum_network: nft-devnet-10
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: prysm-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.nft-devnet-10.ethpandaops.io/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.nft-devnet-10.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.nft-devnet-10.ethpandaops.io/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.nft-devnet-10.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.nft-devnet-10.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.nft-devnet-10.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
