# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-cl.yaml.j2
# Consensus layer endpoints

- url: http://prysm-geth-001:5052
  name: rpc-prysm-geth-001
  authGroup: pandaops
  archive: true
  priority: 1
- url: https://bn-bootnode-1.srv.nft-devnet-10.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
- url: https://bn-lighthouse-besu-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-besu-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-besu-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-besu-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-erigon-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-erigon-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-erigon-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-erigon-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-geth-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-geth-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-geth-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nethermind-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nethermind-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nimbusel-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nimbusel-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-nimbusel-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nimbusel-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-reth-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-reth-1
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lighthouse-reth-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-reth-2
  authGroup: pandaops
  priority: -1
  archive: true
- url: https://bn-lodestar-geth-1.srv.nft-devnet-10.ethpandaops.io
  name: lodestar-geth-1
  authGroup: pandaops
  priority: -1

