# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: http://geth-prysm-001:8545
  name: rpc-prysm-geth-001
  authGroup: pandaops
  archive: true
  priority: 1
- url: https://rpc-bootnode-1.srv.nft-devnet-10.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-bootnode-1.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-besu-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-besu-1.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-besu-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-besu-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-besu-2.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-erigon-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-erigon-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-erigon-1.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-erigon-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-erigon-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-erigon-2.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-1.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-geth-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-geth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-geth-2.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-nethermind-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-nethermind-1.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-nethermind-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nethermind-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-nethermind-2.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-nimbusel-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nimbusel-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-nimbusel-1.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-nimbusel-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-nimbusel-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-nimbusel-2.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-reth-1.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-reth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-reth-1.srv.nft-devnet-10.ethpandaops.io:8961
- url: https://rpc-lighthouse-reth-2.srv.nft-devnet-10.ethpandaops.io
  name: lighthouse-reth-2
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc-lighthouse-reth-2.srv.nft-devnet-10.ethpandaops.io:8961
